### PR TITLE
Republish for scala native 0.5

### PR DESCRIPTION
**Pull request by adrianabreu**
I'd like to test the library for a small Scala Native project using Scala 3.3.3.
I've done my best to upgrade both the build definition and the interop methods. 
Although I know this hasn't been maintained for a while,
 I would appreciate it if you could do some checks. 

Thank you!

### CODE REVIEW

**Comment by david-bouyssie** [comment]
Thank you for your contribution.
Unfortunately CI failed:
```
[error] Found 1 unreachable symbols!
[error] Unknown type scala.jdk.CollectionConverters$, referenced from:
[error]          method scribe.mdc.MDCMap.map(): scala.collection.immutable.Map at MDCMap.scala:12
[error]          method scribe.LoggerSupport$.apply(scribe.Level, scala.collection.immutable.List, sourcecode.Pkg, sourcecode.FileName, sourcecode.Name, sourcecode.Line, scribe.mdc.MDC): scribe.LogRecord at LoggerSupport.scala:115
[error]          method scribe.LoggerSupport.log(scribe.Level, scribe.mdc.MDC, scala.collection.Seq, sourcecode.Pkg, sourcecode.FileName, sourcecode.Name, sourcecode.Line): java.lang.Object at LoggerSupport.scala:16
[error]          method scribe.Logger.log(scribe.Level, scribe.mdc.MDC, scala.collection.Seq, sourcecode.Pkg, sourcecode.FileName, sourcecode.Name, sourcecode.Line): scala.runtime.BoxedUnit at Logger.scala:71
[error]          method scribe.Logger.log(scribe.Level, scribe.mdc.MDC, scala.collection.Seq, sourcecode.Pkg, sourcecode.FileName, sourcecode.Name, sourcecode.Line): java.lang.Object at Logger.scala:18
[error]          method scribe.LoggerSupport.info(scala.collection.Seq, sourcecode.Pkg, sourcecode.FileName, sourcecode.Name, sourcecode.Line, scribe.mdc.MDC): java.lang.Object at LoggerSupport.scala:[37](https://github.com/david-bouyssie/sqlite4s/actions/runs/9358348448/job/25772765597?pr=7#step:4:38)
[error]          method scribe.Logger.info(scala.collection.Seq, sourcecode.Pkg, sourcecode.FileName, sourcecode.Name, sourcecode.Line, scribe.mdc.MDC): java.lang.Object at Logger.scala:1
```

I would need a bit of time to debug this.

**Comment by david-bouyssie** [comment]
BTW could you please change the first SBT settings by those ones:
```
name := "sqlite4s"
organization := "com.github.david-bouyssie"
version := "0.6.0"
scalaVersion := "3.3.3"
crossScalaVersions := Seq("3.3.3", "2.13.14", "2.12.19")
```

I would like to keep the sqlite4s version under 1.0 because some features (long array binding, job queue) are not yet implemented.  Now that Scala Native supports multi-threading I could try to implement the missing "job queue" feature.

I will debug the issue.

**Comment by adrianabreu** [comment]
> BTW could you please change the first SBT settings by those ones:
> 
> ```
> name := "sqlite4s"
> organization := "com.github.david-bouyssie"
> version := "0.6.0"
> scalaVersion := "3.3.3"
> crossScalaVersions := Seq("3.3.3", "2.13.14", "2.12.19")
> ```
> 
> I would like to keep the sqlite4s version under 1.0 because some features (long array binding, job queue) are not yet implemented. Now that Scala Native supports multi-threading I could try to implement the missing "job queue" feature.
> 
> I will debug the issue.

Oh, wow thanks! Absolutely. I just pushed the changes for version 0.6.0 and cross-scala versions. 

I also tried to dig into how java.util.loader is implemented. Got this https://github.com/scala-native/scala-native/commit/51dc81e089deefbd02ebe8414cd1e4dc3bc0cd3f but couldn't figure it

**Comment by adrianabreu** [comment]
Oh I may have found it. scribe 3.14.0 is using scala-compats 2.11.0 which doesn't support scala-native 0.5.X. 
Will try to double check on the scribe project

**Comment by david-bouyssie** [comment]
I filed an issue on the scribe repo.
Waiting for a new release...

**Comment by adrianabreu** [comment]
Yup, scribe 3.15.0 was released! All +tests  and +compile working on my side :)

**Comment by david-bouyssie** [comment]
Done. I'll try to publish soon.

**Pull request merged**
