### PR TITLE
Support Scala 3

### PR DESCRIPTION
**Pull request by lolgab**
- Move CONSTANTS objects to top level (not supported in Scala 3)
- Bump Scala Native to 0.4.4
- Bump Sbt to 1.6.2

### CODE REVIEW

**Comment by david-bouyssie** [comment]
Thank you @lolgab for this very nice PR.

It looks good to me except for one point, the `@BeanProperty` annotation.
Is there a problem with `scala.beans.BeanProperty` in Scala 3.

The main purpose was to align the sqlite4s API with the sqlite4java one.

**Comment by lolgab** [comment]
`@BeanProperty` doesn't seem to be supported by Scala 3. So I wrote the getters by hand for the fields that had it.
API-wise it should be equivalent, with the drawback that now you'll need to maintain the getters yourself, but it's 4 lines of code, so not a big deal.

**Comment by david-bouyssie** [comment]
I see, I found more information here:
https://github.com/lampepfl/dotty/issues/11972
https://docs.scala-lang.org/scala3/guides/migration/incompat-other-changes.html#invisible-bean-property

So in that case I think manual getter/setter is the way to go if sqlite4s API should be 100% aligned with sqlite4java.
What do you think?

**Comment by lolgab** [comment]
I agree. Here you're not making available a Scala API to Java but porting a Java API to Scala, so it makes sense to make the getters available to everyone.

**Pull request merged**
